
package proyectoesquizofrenia;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import org.jpl7.Query;


public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setTitle("DIAGNOSTICO DE LA ESQUIZOFRENIA");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("SISTEMA EXPERTO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 342, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(132, 37, 220));
        jLabel2.setText("DIAGNOSTICO DE LA ESQUIZOFRENIA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 590, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 350, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 350, 20));

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 204, 51));
        jButton1.setText("INICIAR DIAGNOSTICO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 204, 0));
        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 590, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 354, 510, 250));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoesquizofrenia/cuatro.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 220, 190));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoesquizofrenia/medico.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 440, 480));

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Para comenzar el examen dar clic en INICIAR DIAGNOSTICO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        jLabel6.setText("**************************************************************");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        jLabel7.setText("Responda toda las Preguntas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 350, 10));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 350, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String conexion = "consult('Proyecto-Esquizofrenia.pl')";
        Query objConsulta = new Query (conexion);
        
        
            System.out.println(conexion + "" + (objConsulta.hasMoreSolutions() ? "CONEXION EXITOSA":"CONEXION FALLIDA"));
            //System.out.println(conexion +"  "+(objConsulta.hasSolution()?"exito":"falla"));
        
            
         int p, d,c,s,r ;
         
         p=JOptionPane.showConfirmDialog(rootPane, "Usted Presenta signos de ESQUIZOFRENIA PARANOIDE?",null,YES_NO_OPTION);
         
         if(p==0){
             esquizofrenia_paranoide();
         }
         
         else if(p==1){
             d=JOptionPane.showConfirmDialog(rootPane, "Usted Presenta signos de ESQUIZOFRENIA DESORGANIZADO?",null,YES_NO_OPTION);
                if(d==0){
                   esquizofrenia_desorganizado(); 
                }
                else if(d==1){
                   c=JOptionPane.showConfirmDialog(rootPane, "Usted Presenta signos de ESQUIZOFRENIA CATOTICO?",null,YES_NO_OPTION); 
                        if(c==0){
                           esquizofrenia_catotico(); 
                        }
                        else if(c==1){
                            s=JOptionPane.showConfirmDialog(rootPane, "Usted Presenta signos de ESQUIZOFRENIA SIMPLE?",null,YES_NO_OPTION);
                                if(s==0){
                                    esquizofrenia_simple();
                                }
                                else if(s==1){
                                    r=JOptionPane.showConfirmDialog(rootPane, "Usted Presenta signos de ESQUIZOFRENIA RESIDUAL?",null,YES_NO_OPTION);
                                        if(r==0){
                                           esquizofrenia_residual(); 
                                        }
                                        else if(r==1){
                                            JOptionPane.showConfirmDialog(rootPane, "Usted no presenta ninguna las 5 enfermedades de la esquizofrenia?",null,YES_NO_OPTION);
                                        }
                                }
                        }
                }
             
             
         }  
            
    }//GEN-LAST:event_jButton1ActionPerformed

    public void esquizofrenia_paranoide(){
        
        int uno,dos,tres,cuatro;
        
        uno=JOptionPane.showConfirmDialog(rootPane, "¿Tiene ideas delirantes que son de persecución de perjuicio?",null,YES_NO_OPTION);
        dos=JOptionPane.showConfirmDialog(rootPane, "¿Tiene ideas delirantes con otra temática?",null,YES_NO_OPTION);
        tres=JOptionPane.showConfirmDialog(rootPane, "¿Tiene alucinaciones que van con la temática delirante?",null,YES_NO_OPTION);
        cuatro=JOptionPane.showConfirmDialog(rootPane, "¿Tiene ansiedad, ira, retraimiento y tendencia a discutir?",null,YES_NO_OPTION);
        
        if((uno==0)&&(dos==0)&&(tres==0)&&(cuatro==0)){
        
        String dg ="\n"
                  +"\n"
                  +"                      SISTEMA EXPERTO DE DIAGNOSTICO DE LA ESQUIZOFRENIA\n" 
                  +"\n"
                  +"                                                   Ing. de Sistemas\n"
                  +"******************************************************************************************\n"
                  +"\n"
                  +"     DIAGNOSTICO:\n" 
                  +"\n"
                  +"     Lo que Usted presenta es la enfermedad de la ESQUIZOFRENIA PARANOIDE  \n"
                  +"*******************************************************************************************\n"
                  +"\n"
                  +"                      TRATAMIENTO:\n" 
                  +"\n"
                  +"  #. Psicoterapia \n"
                  +"  #. Establecer confianza y clima de honestidad \n"
                  +"  #. Tono profesional \n"
                  +"  #. La terapia conductual puede ser util \n"
                  +"  #. Terapia de apoyo individual \n"
                  +"  #. Terapia de apoyo grupal \n"
                  +"  #. Farmacoterapia: Diazepan, Tioridazina, Haloperidos."
                ;
        
        jTextArea1.setText(dg);
       }
        else{
            esquizofrenia_desorganizado();
        }
    }
    
    public void esquizofrenia_desorganizado(){
        
        int uno,dos,tres,cuatro;
        
        uno=JOptionPane.showConfirmDialog(rootPane, "¿Tiene un lenguaje desorganizado?",null,YES_NO_OPTION);
        dos=JOptionPane.showConfirmDialog(rootPane, "¿Tiene un comportamiento desorganizado?",null,YES_NO_OPTION);
        tres=JOptionPane.showConfirmDialog(rootPane, "¿Tiene ideas delirantes y alucinaciones?",null,YES_NO_OPTION);
        cuatro=JOptionPane.showConfirmDialog(rootPane, "¿Tiene alteraciones en las emociones?",null,YES_NO_OPTION);
        
        if((uno==0)&&(dos==0)&&(tres==0)&&(cuatro==0)){
            
            String dg ="\n"
                  +"\n"
                  +"                      SISTEMA EXPERTO DE DIAGNOSTICO DE LA ESQUIZOFRENIA\n" 
                  +"\n"
                  +"                                                   Ing. de Sistemas\n"
                  +"******************************************************************************************\n"
                  +"\n"
                  +"     DIAGNOSTICO:\n" 
                  +"\n"
                  +"     Lo que Usted presenta es la enfermedad de la ESQUIZOFRENIA DESORGANIZADO  \n"
                  +"*******************************************************************************************\n"
                  +"\n"
                  +"                      TRATAMIENTO:\n" 
                  +"\n"
                  +"  #. Antipsicóticos  \n"
                  +"  #.   - Paliperidona \n"
                  +"  #.   - Olanzapina \n"
                  +"  #.   - Aripiprazol \n"
                  +"  #. La terapia conductual puede ser util \n"
                  +"  #. Terapia de apoyo individual \n"
                  +"  #. Terapia de apoyo grupal \n"
                    ;
        
        jTextArea1.setText(dg);
            
        }
        else{
            esquizofrenia_catotico();
        }
        
    }
    
    public void esquizofrenia_catotico(){
        
        int uno,dos,tres,cuatro;
        
        uno=JOptionPane.showConfirmDialog(rootPane, "¿tiene inmovilidad?",null,YES_NO_OPTION);
        dos=JOptionPane.showConfirmDialog(rootPane, "¿Tiene actividad motora excesiva?",null,YES_NO_OPTION);
        tres=JOptionPane.showConfirmDialog(rootPane, "¿Tiene mutismo o peculiaridades del movimiento voluntario?",null,YES_NO_OPTION);
        cuatro=JOptionPane.showConfirmDialog(rootPane, "¿Adopta posturas raras o inapropiadas?",null,YES_NO_OPTION);
        
        if((uno==0)&&(dos==0)&&(tres==0)&&(cuatro==0)){
            
            String dg ="\n"
                  +"\n"
                  +"                      SISTEMA EXPERTO DE DIAGNOSTICO DE LA ESQUIZOFRENIA\n" 
                  +"\n"
                  +"                                                   Ing. de Sistemas\n"
                  +"******************************************************************************************\n"
                  +"\n"
                  +"     DIAGNOSTICO:\n" 
                  +"\n"
                  +"     Lo que Usted presenta es la enfermedad de la ESQUIZOFRENIA CATOTICO  \n"
                  +"*******************************************************************************************\n"
                  +"\n"
                  +"                      TRATAMIENTO:\n" 
                  +"\n"
                  +"  #. Antipsicóticos  \n"
                  +"  #.   - Amilsuprida \n"
                  +"  #.   - Aripiprazol \n"
                  +"  #.   - Clozapina \n"
                  +"  #.   - Quetiapina \n"
                  +"  #.   - Risperidona \n"
                  +"  #.   - Ziprasidona \n"
                  +"  #.   - Zotapina \n"
                  +"  #. La terapia conductual puede ser util \n"
                  +"  #. Terapia de apoyo individual \n"
                  +"  #. Terapia de apoyo grupal \n"
                    ;
        
        jTextArea1.setText(dg);
            
        }
        else{
            esquizofrenia_simple();
        }
           
    }
    
    public void esquizofrenia_simple(){
        
        int uno,dos,tres,cuatro;
        
        uno=JOptionPane.showConfirmDialog(rootPane, "¿tiene delirios?",null,YES_NO_OPTION);
        dos=JOptionPane.showConfirmDialog(rootPane, "¿Tiene un embotamiento afectivo?",null,YES_NO_OPTION);
        tres=JOptionPane.showConfirmDialog(rootPane, "¿Tiene alucinaciones?",null,YES_NO_OPTION);
        cuatro=JOptionPane.showConfirmDialog(rootPane, "¿Tiene una desorganización de la conducta?",null,YES_NO_OPTION);
        
        if((uno==0)&&(dos==0)&&(tres==0)&&(cuatro==0)){
            
            String dg ="\n"
                  +"\n"
                  +"                      SISTEMA EXPERTO DE DIAGNOSTICO DE LA ESQUIZOFRENIA\n" 
                  +"\n"
                  +"                                                   Ing. de Sistemas\n"
                  +"******************************************************************************************\n"
                  +"\n"
                  +"     DIAGNOSTICO:\n" 
                  +"\n"
                  +"     Lo que Usted presenta es la enfermedad de la ESQUIZOFRENIA SIMPLE  \n"
                  +"*******************************************************************************************\n"
                  +"\n"
                  +"                      TRATAMIENTO:\n" 
                  +"\n"
                  +"  #. Antipsicóticos Tipicos \n"
                  +"  #.   - Haloperidol \n"
                  +"  #.   - Flufenacina \n"
                  +"  #.   - Clorpromacina \n"
                  +"  #.   - Levomepromacina \n"
                  +"  #.   - Tioridacina \n"
                  +"  #.   - Sulpiride \n"
                  +"  #.   - Clozapina \n"
                  +"  #.   - Risperiodona \n"
                  +"  #.   - Olanzapina \n"
                  +"  #.   - Quetiapina \n"
                  +"  #. La terapia conductual puede ser util \n"
                  +"  #. Terapia de apoyo individual\n"
                  +"  #. Terapia de apoyo grupal \n"
                    ;
        
        jTextArea1.setText(dg);
            
        }
        else{
            esquizofrenia_residual();
        }
        
    }
    
    public void esquizofrenia_residual(){
        
        int uno,dos,tres,cuatro;
        
        uno=JOptionPane.showConfirmDialog(rootPane, "¿Tiene aislamiento emocional?",null,YES_NO_OPTION);
        dos=JOptionPane.showConfirmDialog(rootPane, "¿Tiene aislamiento social?",null,YES_NO_OPTION);
        tres=JOptionPane.showConfirmDialog(rootPane, "¿Tiene pobreza del lenguaje?",null,YES_NO_OPTION);
        cuatro=JOptionPane.showConfirmDialog(rootPane, "¿Tiene  falta de interés en alguna actividad?",null,YES_NO_OPTION);
        
        if((uno==0)&&(dos==0)&&(tres==0)&&(cuatro==0)){
            
            String dg ="\n"
                  +"\n"
                  +"                      SISTEMA EXPERTO DE DIAGNOSTICO DE LA ESQUIZOFRENIA\n" 
                  +"\n"
                  +"                                                   Ing. de Sistemas\n"
                  +"******************************************************************************************\n"
                  +"\n"
                  +"     DIAGNOSTICO:\n" 
                  +"\n"
                  +"     Lo que Usted presenta es la enfermedad de la ESQUIZOFRENIA RESIDUAL  \n"
                  +"*******************************************************************************************\n"
                  +"\n"
                  +"                      TRATAMIENTO:\n" 
                  +"\n"
                  +"  #. La terapia conductual puede ser util \n"
                  +"  #. Terapia de apoyo individual"
                  +"  #. Terapia de apoyo grupal"
                  +"  #. Antipsicóticos  \n"
                  +"  #.   - Haloperidol \n"
                  +"  #.   - Flufenacina \n"
                  +"  #.   - Clorpromacina \n"
                  +"  #.   - Levomepromacina \n"
                  +"  #.   - Tioridacina \n"
                  +"  #.   - Sulpiride \n"
                  +"  #.   - Clozapina \n"
                  +"  #.   - Risperiodona \n"
                  +"  #.   - Olanzapina \n"
                  +"  #.   - Quetiapina \n"
                  
                    ;
        
        jTextArea1.setText(dg);
            
        }
        else{
            esquizofrenia_paranoide();
        }
        
    }
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
